# Generated by Django 4.1.5 on 2023-01-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='indexPage',
        ),
    ]
