# Generated by Django 4.1.5 on 2023-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0002_rename_post_indexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='img',
            field=models.ImageField(blank=True, upload_to='teamlead/', verbose_name='Картинка'),
        ),
    ]
