# Generated by Django 4.1.5 on 2023-01-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0003_indexpage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpage',
            old_name='text',
            new_name='text1',
        ),
    ]
