# Generated by Django 4.1.5 on 2023-01-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0004_rename_text_indexpage_text1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='img',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
