# Generated by Django 4.1.5 on 2023-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0007_list_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='headerAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='teamlead/', verbose_name='Логотип')),
                ('name', models.TextField(verbose_name='Название сайта')),
            ],
        ),
        migrations.CreateModel(
            name='latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Заголовок')),
            ],
        ),
        migrations.DeleteModel(
            name='list_vacancies',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='name',
            field=models.TextField(default=1, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
