# Generated by Django 4.1.5 on 2023-01-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0009_alter_headeradm_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='geography',
            new_name='demandAd',
        ),
        migrations.RenameModel(
            old_name='demand',
            new_name='geographyAd',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='latestAd',
        ),
        migrations.RenameModel(
            old_name='latest',
            new_name='skillsAd',
        ),
    ]
