# Generated by Django 4.1.5 on 2023-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0010_rename_geography_demandad_rename_demand_geographyad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='headerAdm',
        ),
        migrations.AddField(
            model_name='demandad',
            name='logo',
            field=models.ImageField(blank=True, upload_to='header/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='demandad',
            name='nameSite',
            field=models.TextField(default=1, verbose_name='Название сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geographyad',
            name='logo',
            field=models.ImageField(blank=True, upload_to='header/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='geographyad',
            name='nameSite',
            field=models.TextField(default=1, verbose_name='Название сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestad',
            name='logo',
            field=models.ImageField(blank=True, upload_to='header/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='latestad',
            name='nameSite',
            field=models.TextField(default=1, verbose_name='Название сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillsad',
            name='logo',
            field=models.ImageField(blank=True, upload_to='header/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='skillsad',
            name='nameSite',
            field=models.TextField(default=1, verbose_name='Название сайта'),
            preserve_default=False,
        ),
    ]
