# Generated by Django 4.1.5 on 2023-01-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0012_indexpage_logo_indexpage_namesite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandad',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='demandad',
            name='nameSite',
        ),
        migrations.RemoveField(
            model_name='geographyad',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='geographyad',
            name='nameSite',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='nameSite',
        ),
        migrations.RemoveField(
            model_name='latestad',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='latestad',
            name='nameSite',
        ),
        migrations.RemoveField(
            model_name='skillsad',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='skillsad',
            name='nameSite',
        ),
    ]
